#!/bin/bash -x
#
# Test for a reboot,  if this is a reboot just skip this script.
#
if test "$RS_REBOOT" = "true" ; then
  echo "Skip re-install on reboot."
  exit 0
fi

wget -q -O - http://hudson-ci.org/debian/hudson-ci.org.key | apt-key add -

echo "deb http://hudson-ci.org/debian binary/" > /etc/apt/sources.list.d/hudson.list

apt-get update
apt-get install hudson

exit
